### ISSUE TITLE
Promise rejection. An error has occurred, please fix the error.

### ISSUE THREAD

**Issue by shujaathaider** [uzochukwueddie/fixer-io-node#1]
I am suddenly getting the error. Has anything changed?

```
var currencyConvert = require('fixer-io-node');
currencyConvert.base('USD').then(function(result){
    console.log("1 USD = " + result.rates.CHF +" CHF ")
    USDtoCHF = result.rates.CHF.toFixed(2);
}).catch(function(error){
    console.log(error)
})
```

**Comment by homayeekazim** [comment]
Please fix this asap.

**Comment by uzochukwueddie** [comment]
hey thanks for contacting me. Nothing has changed in the module

Best Regards
Eddie

**Comment by onevcat** [comment]
@uzochukwueddie This was due to fixer.io began to redirect the HTTP requests (http://api.fixer.io) to HTTPS entry point (https://api.fixer.io) with a 301 status code. And the status code is not considered as success. According to fixer's documentation, I believe we should use https instead.

> Get the latest foreign exchange reference rates.
> `https://api.fixer.io/latest`

(BTW, now HTTP requests to fixer.io could return a normal 200. But it still a good idea to just use HTTPS in client.)

**Comment by homayeekazim** [comment]
@uzochukwueddie - I have sent you a pull request. Have changed http to https request. Please pull.

**Comment by uzochukwueddie** [comment]
Thanks man i'll do it right away
